/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parser;

import org.junit.Test;
import static org.junit.Assert.*;

import java.text.ParseException;

public class RecognizerTest {

  @Test
  public void EasyTest() {
    Recognizer recognizer = new Recognizer("1.");
    try {
      recognizer.recognize();
    } catch(ParseException e) {
      fail();
    }
  }

  @Test
  public void LargeNumbersTest() {
    Recognizer recognizer = new Recognizer("1123-732+19*d531.");
    try {
      recognizer.recognize();
    } catch(ParseException e) {
      fail();
    }
  }

  @Test
  public void EasyParanTest() {
    Recognizer recognizer = new Recognizer("(1).");
    try {
      recognizer.recognize();
    } catch(ParseException e) {
      fail();
    }
  }

  @Test
  public void NestedParanTest() {
    Recognizer recognizer = new Recognizer("((1)+(2)).");
    try {
      recognizer.recognize();
    } catch(ParseException e) {
      fail();
    }
  }

  @Test
  public void AddTest() {
    Recognizer recognizer = new Recognizer("1+2.");
    try {
      recognizer.recognize();
    } catch(ParseException e) {
      fail();
    }
  }

  @Test
  public void MinusTest() {
    Recognizer recognizer = new Recognizer("4-1.");
    try {
      recognizer.recognize();
    } catch (ParseException e) {
      fail();
    }
  }

  @Test
  public void DoubleOperatorTest() {
    Recognizer recognizer = new Recognizer("4-+1.");
    try {
      recognizer.recognize();
      fail();
    } catch(ParseException e) {
      // Success
    }
  }

  @Test
  public void DoubleOperatorTest2() {
    Recognizer recognizer = new Recognizer("4*/1.");
    try {
      recognizer.recognize();
      fail();
    } catch(ParseException e) {
      // Success
    }
  }

  @Test
  public void NegateTest() {
    Recognizer recognizer = new Recognizer("-42.");
    try {
      recognizer.recognize();
    } catch (ParseException e) {
      fail();
    }
  }
}
